---
- name: Install Docker
  hosts: staging_server
  become: yes

  tasks:
   - name: Block for Ubuntu
     block:
       - name: Update and upgrade apt packages
         apt:
          upgrade: yes
          update_cache: yes
  
       - name: Install packages
         apt: name={{ item }} state=present
         loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

       - name: Add Docker’s official GPG key
         apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

       - name: "APT - Add Docker repository"
         apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
          state: present
          filename: docker

       - name: Update and upgrade apt packages
         apt:
           upgrade: yes
           update_cache: yes

       - name: Install docker-ce
         apt: name={{ item }} state=present
         loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io 

       - name: Docker check
         shell: docker run hello-world
         register: results
 
       - name: Print output
         debug:
           var: results.stdout
     when: ansible_facts['distribution'] == 'Ubuntu'
